name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3  # Use the latest stable version
        with:
          github_user_name: Rahul-Raval-2912
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push the generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Rahul-Raval-2912
          author_email: your-email@example.com
          message: "Generated Snake Animation"
          add: 'dist/github-contribution-grid-snake.svg'
          push: true
